### ISSUE TITLE
crash on fullscreen

### ISSUE THREAD

**Issue by FluffyBunny294** [batmanatorul/minesettlements-issues#7]
- [X] I am using the latest version of the mod
- [X] I checked if this bug report it's not a duplicate

**Information**
 - Mod Version
 - 1.0 beta
 - Minecraft Version 
 - 1.18.2

**Describe the bug**
Minecraft crashes whenever i use the new settlement gamemode and fullscreen together.

**To Reproduce**
1. go into fullscreen
2. load any world with the settlement gamemode

**Expected behavior**
not crashing when using fullscreen

**Screenshots**
Send some screenshots if applicable

**More Info**
[crash-2022-09-04_12.30.32-client.txt](https://github.com/batmanatorul/minesettlements-issues/files/9484724/crash-2022-09-04_12.30.32-client.txt)
[latest.log](https://github.com/batmanatorul/minesettlements-issues/files/9484726/latest.log)
these are my logs when producing the crash

**Comment by batmanatorul** [comment]
I think I solved it, but i can't 100% know if I did because it didn't happen to me
