### ISSUE TITLE
[Bug]: locked out of world

### ISSUE THREAD

**Issue by FluffyBunny294** [batmanatorul/minesettlements-issues#8]
### Is there already an issue open for this bug?

- [x] I have checked and there is no issue for this yet

### Are you using the latest BETA version available of this mod?

- [X] I have tried to use the latest version

### Minesettlements version

1.0 beta

### Other mods and their versions

```bash
1. Fabric API: 0.58.0
2. GeckoLib: 3.0.59
```

### What is the problem?

```bash
i get a crash any time i try to load into a world with an animal hunting area in it
```

### Reproduction steps

```bash
1. place an animal hunting area in the world
2. exit the world
3. enter the world
```

### Logs

https://gist.github.com/FluffyBunny294/14c07317dba05df5987ed94f2be6580d

**Comment by batmanatorul** [comment]
Will be solved in the next update 👍
